### PR TITLE
Fix local files query string ENOENT exception.

### PR DESCRIPTION
**Pull request by patrikholcak**
Turns out fs doesn’t particularly enjoy having a query string in a file name and throws a “file not found” error. But fear not! This patch is here to the rescue!

But seriously, though…
`<link rel="stylesheet" href="/main.css?v=1445367009869"/>` does not work and this patch should fix it. Or at least it works for me!

### CODE REVIEW

**Comment by bezoerb** [comment]
Nice catch. Can you provide a test for your fix?

**Comment by patrikholcak** [comment]
Yup. Will do tomorrow.

**Comment by patrikholcak** [comment]
Done and dusted. The test seems to pass fine!

**Comment by bezoerb** [comment]
LGTM

**Pull request merged**
