### PR TITLE
support CleanCSS option

### PR DESCRIPTION
**Pull request by orthes**
Since the project is using CleanCSS for minification, it makes sense to expose `cleancss` option that would get passed down to `new CleanCSS()` so if somebody chooses to go beyond CleanCSS' default options, they can do so.

### CODE REVIEW

**Comment by bezoerb** [comment]
@orthes: can you add cli support, too?

And maybe it's more future proof to use the minify option so we're able to change the minifyer without changing the process.
`true` or options `object` = minify
`false` = no minify

**Comment by orthes** [comment]
@bezoerb good feedback. Sure, that makes sense. I'll look into it.

**Comment by XhmikosR** [comment]
That's not a rebase FYI.

**Comment by orthes** [comment]
I'll create a separate PR. I don't know why this one ended up in this state

**Pull request closed without merging**
