### PR TITLE
Vinyl

### PR DESCRIPTION
**Pull request by bezoerb**
This is a bigger maintenance PR. It includes the following improvements:
* Can handle vinyl file objects (#119)
* Determine `pathPrefix` automatically in most cases which drops the need for absolute asset paths. Asset paths will now stay relative (relative to the html file) if they were relative in the stylesheets (#57,#95)
* Improved handling of html files in subfolders

### CODE REVIEW

**Comment by bezoerb** [comment]
still needs some work

**Comment by Tempurturtul** [comment]
In index.js:

```javascript
exports.stream = function (opts) {
    // ...
        var options = _.assign(opts || {}, {
            // src: file
            src: file.path
        });
    // ...
```

Seems to provide correct behavior in my test cases.

**Comment by bezoerb** [comment]
@addyosmani wanna take a look?

**Comment by addyosmani** [comment]
Yep. Sorry I've been out of town for a few weeks but I'll take a look. Thanks for working on this :star:

**Comment by bezoerb** [comment]
Still needs some work (see https://github.com/addyosmani/critical/issues/57)
Asset paths should be computed relative to `dest` instead of the src path.
When no `dest` is available we need a target path option which should default to the src path

**Comment by bezoerb** [comment]
\o/ green again :)

Added `destFolder` option used to compute the relative asset path. 
Asset paths are now computed in this order:
* relative to `destFolder` if option is set
* relative to `dest` if option is set
* relative to `src` file 

@addyosmani: Want to take a look again? (Sorry for the 31 changed files ;))

**Comment by addyosmani** [comment]
Thanks for working on this! I'll take a look in the morning :)

**Comment by addyosmani** [comment]
The list of changes here on the whole LGTM. To avoid blocking any further work here lets land it.

**Pull request merged**
