### PR TITLE
Headless chrome

### PR DESCRIPTION
**Pull request by bezoerb**

### CODE REVIEW

**Comment by bezoerb** [comment]
Travis is green now :)
We should remove all deprecated methods, fix at least #171 and #244 and finally go for v1.0.0

**Comment by developer-lindner** [comment]
Go?

**Comment by shervud** [comment]
Hi everyone.
I have a question. In my project I use node 4.4.2 , so I don't have a chance to update my node to >=6 version.
More over, I use grunt-critical (by bezoerb) v.0.3.0 which is based on critical (current module) with 0.9.0 version.
What my config of dependencies should be to run on node version >=4 my grunt-critical and of cource critical?

Thank you very much!

**Comment by bezoerb** [comment]
@shervud: [`grunt-critical`](https://github.com/bezoerb/grunt-critical) should work fine in an node v4 environment. The next versions of `critical` and `grunt-critical` will however require node >= 6.

**Comment by shervud** [comment]
@bezoerb yeah, thank you. 
By the way, I'm still looking for the way of using grunt-critical v 0.3.0 at node >=4 & <= 6. All I need is to get features from penthouse (renderWaitTime, blockJSRequests) which occurs in its 0.10.3 version.
Would you know may be...
Is there a way to make it? May be by using npm-shrinkwrap to lock versions of several packages, etc...

**Comment by bezoerb** [comment]
[v1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.0.0) Released :)

**Pull request merged**
