### PR TITLE
Remote critical

### PR DESCRIPTION
**Pull request by bezoerb**
This PR enables critical to be used over the wire. 
**CLI**
```bash
critical http://getbootstrap.com/ -m 
```

**MODULE**
```javascript
critical.generate({
    src: 'http://getbootstrap.com/',
    minify: true
}).then(...)
```
Issues #19, #90, and #94

Also added a garbage collector to remove the temporary files generated by critical to address #82

### CODE REVIEW

**Comment by bezoerb** [comment]
@addyosmani I think this one's ready to merge. Do you wanna take a look before merging or are you confident everything's fine

**Comment by bezoerb** [comment]
so i guess you're fine with the changes ;)

**Comment by addyosmani** [comment]
Whoops. Was looking at this yesterday and thought I had LGTMd. A late LGTM :) Thanks!

**Comment by SerzN1** [comment]
Hi @addyosmani . Does not work today with gulp `npm install --save critical`.

**Comment by bezoerb** [comment]
@SerzN1 this is not released yet.
Try `npm install --save git+https://github.com/addyosmani/critical.git`

**Pull request merged**
