### PR TITLE
Allow multiple --css flags in cli fixes #514

### LINKED ISSUE #514: Bug: The flag --css can only be set once
Since v2.0:
The flag --css can only be set once

--css is an array, then multiple -css flags should be allowed as it was before v2.0

### PR DESCRIPTION
**Pull request by josenobile**
Multiple --css flags were lost in v2.0, this restores the possibility of multiple --css flags
Fixes #514

### CODE REVIEW

**Comment by josenobile** [comment]
Hello @addyosmani, looks like some cli acceptance test crashed (Returned empty), can you please give a quick look if it can be related to the isMultiple attribute added to --css flag?

**Comment by bezoerb** [comment]
Hey @josenobile, sorry for the late reply.
It seems like the `isMultiple` is causing the error.
When the css option is set, critical doesn't process the css files listed in the html source. Due to the `isMultiple` flag the css option is an empty array instead of `undefined` (See https://github.com/addyosmani/critical/blob/e3a4e8cdfaf52d7693bb077c7e0f7902c8ee97b9/src/file.js#L867)

I think you should either unset the css option in `cli.js` when it's an empty array or the check in `file.js` needs to be modified

**Comment by josenobile** [comment]
Hello @bezoerb,  Can you please help me to check why it fails two tests? 'Take html file piped to critical' and 'Pipe html file inside a folder to critical'

**Comment by bezoerb** [comment]
Hey @josenobile, 
sorry for the late response. I found the error. See linked PR

**Pull request closed without merging**
