### PR TITLE
README.md: optimize the Preview image

### PR DESCRIPTION
**Pull request by XhmikosR**
@bezoerb: which one do you prefer? The original dimensions or half which looks good on retina too?

BTW if we have the original image I can redo this properly.

Original: https://github.com/addyosmani/critical/blob/bc4b1bce7232d608097cd6efcccd77979caa92e2/README.md#critical
Half: https://github.com/addyosmani/critical/blob/e2775bc89b9b922cdc456287acb3b3bfbfc7f2ff/README.md#critical

### CODE REVIEW

**Comment by bezoerb** [comment]
I think the "half" one looks nicer :)

**Comment by bezoerb** [comment]
The image is not visible on mobile
/cc @XhmikosR

**Comment by XhmikosR** [comment]
Yeah I was using the wrong branch name, I fixed it now in master.

**Comment by bezoerb** [comment]
👍🏼

**Pull request merged**
