### PR TITLE
fix: remove duplicates from getStylesheetHrefs

### PR DESCRIPTION
**Pull request by joejordanbrown**
## Critical produces duplicate CCSS. 

It happens when a page has duplicate link hrefs.

A typical scenario, when a `link ` is wrapped with a `noscript` critical retrieves both hrefs.

**Example:**

```HTML
<link as="style" rel="preload" onload="this.rel='stylesheet'" href="wp-includes/css/dist/block-library/style.min.css" media="all" />
<noscript>
  <link rel="stylesheet" href="wp-includes/css/dist/block-library/style.min.css" media="all" />
</noscript>
```
------

I will follow up with `file.test.js` and update `file.js` so it passes xo test.

### CODE REVIEW

**Comment by joejordanbrown** [comment]
After thinking about this, the `noscript` issue should be resolved in [oust](https://github.com/addyosmani/oust) to prevent `noscript` in the first place. 

This could be added via an optional true/false not to create a breaking change for `oust`, even though it's unlikely people would want `noscript` by default.

Still, getStylesheetHrefs should defiently remove duplicates.

**Comment by joejordanbrown** [comment]
It would also be possible to filter `noscript` if you prefer not to add an option https://github.com/addyosmani/oust/pull/24.

```javascript
function getStylesheetHrefs(file) {
  if (!Vinyl.isVinyl(file)) {
    throw new Error('Parameter file needs to be a vinyl object');
  }

  const stylesheets = oust.raw(file.contents.toString(), 'stylesheets');
  const preloads = oust.raw(file.contents.toString(), 'preload');

  return [...stylesheets, ...preloads]
    .filter(link => link.$el.attr('media') !== 'print' && Boolean(link.value))
    .filter(link => link.$el.parents('noscript').length === 0)
    .map(link => link.value);
}
```

**Comment by bezoerb** [comment]
Hey @joejordanbrown,
thanks for the PR. I think this should be handled in critical. Could you fix the the prettier issues and add a test case for this?
Thanks :)

**Comment by XhmikosR** [comment]
Only tests are left.

**Comment by bezoerb** [comment]
Thanks @XhmikosR 
@joejordanbrown: Any chances we can get a test case for this?

**Comment by bezoerb** [comment]
fixed in b7d2e27771a29431c081f55483859c1693b62598

**Pull request closed without merging**
